## Event detection results

In [17]:
import pandas as pd
import os
import json

In [ ]:
ESTBERT_RESULTS_DIR = 'results/EstBERT'
ESTROBERTA_RESULTS_DIR = 'results/Est-RoBERTa'

#### Methods

In [ ]:
def get_train_res(file, metrics):
    data = None
    with open(file) as f:
        data = json.load(f)
    res_dict = dict()
    for metric in metrics:
        res_dict[f'train_{metric}'] = round(data[metric], 2)
    return res_dict

def get_test_res(file, eval_method, metrics):
    data = None
    with open(file) as f:
        data = json.load(f)
    res_dict = dict()
    for metric in metrics:
        res_dict[f'final_test_{metric}'] = round(data[0][eval_method][metric], 2)
    return res_dict

def get_pred_res(file, eval_method, metrics):
    data = None
    with open(file) as f:
        data = json.load(f)
    res_dict = dict()
    for metric in metrics:
        res_dict[f'pred_{metric}'] = round(data[0][eval_method][metric], 2)
    return res_dict

def fill_res_dict(res_dict, model_cat, path, event_type):
    for filename in os.listdir(path):
        if 'best_eval' in filename:
            res = get_train_res(os.path.join(path, filename), ['eval_precision', 'eval_recall', 'eval_f1'])
            res_dict[model_cat][f'train_eval_{event_type}'] = res
        elif 'best_final_test' in filename:
            res = get_test_res(os.path.join(path, filename), 'strict', ['precision', 'recall', 'f1'])
            res_dict[model_cat][f'final_test_{event_type}'] = res
        elif 'pred_tempf' in filename:
            res = get_pred_res(os.path.join(path, filename), 'strict', ['recall'])
            if 'rkogu' in filename:
                res_dict[model_cat][f'pred_tempf_{event_type}_rkogu'] = res
            elif 'horisont' in filename:
                res_dict[model_cat][f'pred_tempf_{event_type}_horisont'] = res
            elif 'news' in filename:
                res_dict[model_cat][f'pred_tempf_{event_type}_news'] = res

In [21]:
# EstBERTi tulemused sündmuste kõigil sõnadel ja ainult peasõnadel
estbert_res = {'EstBERT_no_classes': {}, 'EstBERT_w_classes': {}, 'EstBERT_w_agg_classes': {}, 'EstBERT_w_agg_classes_no_modal': {}}

# ilma klassideta
fill_res_dict(estbert_res, 'EstBERT_no_classes', f"{ESTBERT_RESULTS_DIR}/events/all", 'all')
fill_res_dict(estbert_res, 'EstBERT_no_classes', f"{ESTBERT_RESULTS_DIR}/events/main", 'main')

# klassidega
fill_res_dict(estbert_res, 'EstBERT_w_classes', f"{ESTBERT_RESULTS_DIR}/events_w_class/all", 'all')
fill_res_dict(estbert_res, 'EstBERT_w_classes', f"{ESTBERT_RESULTS_DIR}/events_w_class/main", 'main')

# agregeeritud klassidega (koos eraldi modaalverbide kategooriaga)
fill_res_dict(estbert_res, 'EstBERT_w_agg_classes', f"{ESTBERT_RESULTS_DIR}/events_w_agg_class/all", 'all')
fill_res_dict(estbert_res, 'EstBERT_w_agg_classes', f"{ESTBERT_RESULTS_DIR}/events_w_agg_class/main", 'main')

# agregeeritud klassidega (ilma eraldi modaalverbide kategooriata)
fill_res_dict(estbert_res, 'EstBERT_w_agg_classes_no_modal', f"{ESTBERT_RESULTS_DIR}/events_w_agg_class_no_modal/all", 'all')
fill_res_dict(estbert_res, 'EstBERT_w_agg_classes_no_modal', f"{ESTBERT_RESULTS_DIR}/events_w_agg_class_no_modal/main", 'main')

### EstBERT event detection results

In [22]:
estbert_res

{'EstBERT_no_classes': {'train_eval_all': {'train_eval_precision': 0.85,
   'train_eval_recall': 0.9,
   'train_eval_f1': 0.88},
  'final_test_all': {'final_test_precision': 0.82,
   'final_test_recall': 0.86,
   'final_test_f1': 0.84},
  'pred_tempf_all_horisont': {'pred_recall': 0.66},
  'pred_tempf_all_news': {'pred_recall': 0.79},
  'pred_tempf_all_rkogu': {'pred_recall': 0.64},
  'train_eval_main': {'train_eval_precision': 0.89,
   'train_eval_recall': 0.93,
   'train_eval_f1': 0.91},
  'final_test_main': {'final_test_precision': 0.87,
   'final_test_recall': 0.85,
   'final_test_f1': 0.86},
  'pred_tempf_main_horisont': {'pred_recall': 0.67},
  'pred_tempf_main_news': {'pred_recall': 0.81},
  'pred_tempf_main_rkogu': {'pred_recall': 0.66}},
 'EstBERT_w_classes': {'train_eval_all': {'train_eval_precision': 0.71,
   'train_eval_recall': 0.74,
   'train_eval_f1': 0.72},
  'final_test_all': {'final_test_precision': 0.7,
   'final_test_recall': 0.7,
   'final_test_f1': 0.7},
  'pred_tempf_all_horisont': {'pred_recall': 0.5},
  'pred_tempf_all_news': {'pred_recall': 0.61},
  'pred_tempf_all_rkogu': {'pred_recall': 0.36},
  'train_eval_main': {'train_eval_precision': 0.72,
   'train_eval_recall': 0.75,
   'train_eval_f1': 0.73},
  'final_test_main': {'final_test_precision': 0.7,
   'final_test_recall': 0.74,
   'final_test_f1': 0.72},
  'pred_tempf_main_horisont': {'pred_recall': 0.5},
  'pred_tempf_main_news': {'pred_recall': 0.62},
  'pred_tempf_main_rkogu': {'pred_recall': 0.41}},
 'EstBERT_w_agg_classes': {'train_eval_all': {'train_eval_precision': 0.77,
   'train_eval_recall': 0.76,
   'train_eval_f1': 0.76},
  'final_test_all': {'final_test_precision': 0.73,
   'final_test_recall': 0.71,
   'final_test_f1': 0.72},
  'pred_tempf_all_horisont': {'pred_recall': 0.48},
  'pred_tempf_all_news': {'pred_recall': 0.6},
  'pred_tempf_all_rkogu': {'pred_recall': 0.41},
  'train_eval_main': {'train_eval_precision': 0.79,
   'train_eval_recall': 0.81,
   'train_eval_f1': 0.8},
  'final_test_main': {'final_test_precision': 0.77,
   'final_test_recall': 0.76,
   'final_test_f1': 0.76},
  'pred_tempf_main_horisont': {'pred_recall': 0.49},
  'pred_tempf_main_news': {'pred_recall': 0.62},
  'pred_tempf_main_rkogu': {'pred_recall': 0.39}},
 'EstBERT_w_agg_classes_no_modal': {'train_eval_all': {'train_eval_precision': 0.74,
   'train_eval_recall': 0.78,
   'train_eval_f1': 0.76},
  'final_test_all': {'final_test_precision': 0.74,
   'final_test_recall': 0.74,
   'final_test_f1': 0.74},
  'pred_tempf_all_horisont': {'pred_recall': 0.69},
  'pred_tempf_all_news': {'pred_recall': 0.64},
  'pred_tempf_all_rkogu': {'pred_recall': 0.39},
  'train_eval_main': {'train_eval_precision': 0.75,
   'train_eval_recall': 0.78,
   'train_eval_f1': 0.76},
  'final_test_main': {'final_test_precision': 0.73,
   'final_test_recall': 0.76,
   'final_test_f1': 0.74},
  'pred_tempf_main_horisont': {'pred_recall': 0.61},
  'pred_tempf_main_news': {'pred_recall': 0.63},
  'pred_tempf_main_rkogu': {'pred_recall': 0.44}}}

In [23]:
pd.DataFrame.from_dict({(i,j): estbert_res[i][j] 
                           for i in estbert_res.keys() 
                           for j in estbert_res[i].keys()},
                       orient='index')

                                                         train_eval_precision  \
EstBERT_no_classes             train_eval_all                            0.85
                               train_eval_main                           0.89
EstBERT_w_classes              train_eval_all                            0.71
                               train_eval_main                           0.72
EstBERT_w_agg_classes          train_eval_all                            0.77
                               train_eval_main                           0.79
EstBERT_w_agg_classes_no_modal train_eval_all                            0.74
                               train_eval_main                           0.75
EstBERT_no_classes             final_test_all                             NaN
                               final_test_main                            NaN
EstBERT_w_classes              final_test_all                             NaN
                               final_test_main                            NaN
EstBERT_w_agg_classes          final_test_all                             NaN
                               final_test_main                            NaN
EstBERT_w_agg_classes_no_modal final_test_all                             NaN
                               final_test_main                            NaN
EstBERT_no_classes             pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_classes              pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN

                                                         train_eval_recall  \
EstBERT_no_classes             train_eval_all                         0.90
                               train_eval_main                        0.93
EstBERT_w_classes              train_eval_all                         0.74
                               train_eval_main                        0.75
EstBERT_w_agg_classes          train_eval_all                         0.76
                               train_eval_main                        0.81
EstBERT_w_agg_classes_no_modal train_eval_all                         0.78
                               train_eval_main                        0.78
EstBERT_no_classes             final_test_all                          NaN
                               final_test_main                         NaN
EstBERT_w_classes              final_test_all                          NaN
                               final_test_main                         NaN
EstBERT_w_agg_classes          final_test_all                          NaN
                               final_test_main                         NaN
EstBERT_w_agg_classes_no_modal final_test_all                          NaN
                               final_test_main                         NaN
EstBERT_no_classes             pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_classes              pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN

                                                         train_eval_f1  \
EstBERT_no_classes             train_eval_all                     0.88
                               train_eval_main                    0.91
EstBERT_w_classes              train_eval_all                     0.72
                               train_eval_main                    0.73
EstBERT_w_agg_classes          train_eval_all                     0.76
                               train_eval_main                    0.80
EstBERT_w_agg_classes_no_modal train_eval_all                     0.76
                               train_eval_main                    0.76
EstBERT_no_classes             final_test_all                      NaN
                               final_test_main                     NaN
EstBERT_w_classes              final_test_all                      NaN
                               final_test_main                     NaN
EstBERT_w_agg_classes          final_test_all                      NaN
                               final_test_main                     NaN
EstBERT_w_agg_classes_no_modal final_test_all                      NaN
                               final_test_main                     NaN
EstBERT_no_classes             pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_classes              pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN

                                                         final_test_precision  \
EstBERT_no_classes             train_eval_all                             NaN
                               train_eval_main                            NaN
EstBERT_w_classes              train_eval_all                             NaN
                               train_eval_main                            NaN
EstBERT_w_agg_classes          train_eval_all                             NaN
                               train_eval_main                            NaN
EstBERT_w_agg_classes_no_modal train_eval_all                             NaN
                               train_eval_main                            NaN
EstBERT_no_classes             final_test_all                            0.82
                               final_test_main                           0.87
EstBERT_w_classes              final_test_all                            0.70
                               final_test_main                           0.70
EstBERT_w_agg_classes          final_test_all                            0.73
                               final_test_main                           0.77
EstBERT_w_agg_classes_no_modal final_test_all                            0.74
                               final_test_main                           0.73
EstBERT_no_classes             pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_classes              pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont                    NaN
                               pred_tempf_all_news                        NaN
                               pred_tempf_all_rkogu                       NaN
                               pred_tempf_main_horisont                   NaN
                               pred_tempf_main_news                       NaN
                               pred_tempf_main_rkogu                      NaN

                                                         final_test_recall  \
EstBERT_no_classes             train_eval_all                          NaN
                               train_eval_main                         NaN
EstBERT_w_classes              train_eval_all                          NaN
                               train_eval_main                         NaN
EstBERT_w_agg_classes          train_eval_all                          NaN
                               train_eval_main                         NaN
EstBERT_w_agg_classes_no_modal train_eval_all                          NaN
                               train_eval_main                         NaN
EstBERT_no_classes             final_test_all                         0.86
                               final_test_main                        0.85
EstBERT_w_classes              final_test_all                         0.70
                               final_test_main                        0.74
EstBERT_w_agg_classes          final_test_all                         0.71
                               final_test_main                        0.76
EstBERT_w_agg_classes_no_modal final_test_all                         0.74
                               final_test_main                        0.76
EstBERT_no_classes             pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_classes              pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont                 NaN
                               pred_tempf_all_news                     NaN
                               pred_tempf_all_rkogu                    NaN
                               pred_tempf_main_horisont                NaN
                               pred_tempf_main_news                    NaN
                               pred_tempf_main_rkogu                   NaN

                                                         final_test_f1  \
EstBERT_no_classes             train_eval_all                      NaN
                               train_eval_main                     NaN
EstBERT_w_classes              train_eval_all                      NaN
                               train_eval_main                     NaN
EstBERT_w_agg_classes          train_eval_all                      NaN
                               train_eval_main                     NaN
EstBERT_w_agg_classes_no_modal train_eval_all                      NaN
                               train_eval_main                     NaN
EstBERT_no_classes             final_test_all                     0.84
                               final_test_main                    0.86
EstBERT_w_classes              final_test_all                     0.70
                               final_test_main                    0.72
EstBERT_w_agg_classes          final_test_all                     0.72
                               final_test_main                    0.76
EstBERT_w_agg_classes_no_modal final_test_all                     0.74
                               final_test_main                    0.74
EstBERT_no_classes             pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_classes              pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_agg_classes          pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN
EstBERT_w_agg_classes_no_modal pred_tempf_all_horisont             NaN
                               pred_tempf_all_news                 NaN
                               pred_tempf_all_rkogu                NaN
                               pred_tempf_main_horisont            NaN
                               pred_tempf_main_news                NaN
                               pred_tempf_main_rkogu               NaN

                                                         pred_recall
EstBERT_no_classes             train_eval_all                    NaN
                               train_eval_main                   NaN
EstBERT_w_classes              train_eval_all                    NaN
                               train_eval_main                   NaN
EstBERT_w_agg_classes          train_eval_all                    NaN
                               train_eval_main                   NaN
EstBERT_w_agg_classes_no_modal train_eval_all                    NaN
                               train_eval_main                   NaN
EstBERT_no_classes             final_test_all                    NaN
                               final_test_main                   NaN
EstBERT_w_classes              final_test_all                    NaN
                               final_test_main                   NaN
EstBERT_w_agg_classes          final_test_all                    NaN
                               final_test_main                   NaN
EstBERT_w_agg_classes_no_modal final_test_all                    NaN
                               final_test_main                   NaN
EstBERT_no_classes             pred_tempf_all_horisont          0.66
                               pred_tempf_all_news              0.79
                               pred_tempf_all_rkogu             0.64
                               pred_tempf_main_horisont         0.67
                               pred_tempf_main_news             0.81
                               pred_tempf_main_rkogu            0.66

In [24]:
# Est-RoBERTa tulemused sündmuste kõigil sõnadel ja ainult peasõnadel
estroberta_res = {'Est-RoBERTa_no_classes': {}, 'Est-RoBERTa_w_classes': {}, 'Est-RoBERTa_w_agg_classes': {}, 'Est-RoBERTa_w_agg_classes_no_modal': {}}

# ilma klassideta
fill_res_dict(estroberta_res, 'Est-RoBERTa_no_classes', f"{ESTROBERTA_RESULTS_DIR}/events/all", 'all')
fill_res_dict(estroberta_res, 'Est-RoBERTa_no_classes', f"{ESTROBERTA_RESULTS_DIR}/events/main", 'main')

# klassidega
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_classes', f"{ESTROBERTA_RESULTS_DIR}/events_w_class/all", 'all')
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_classes', f"{ESTROBERTA_RESULTS_DIR}/events_w_class/main", 'main')

# agregeeritud klassidega (koos eraldi modaalverbide kategooriaga)
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_agg_classes', f"{ESTROBERTA_RESULTS_DIR}/events_w_agg_class/all", 'all')
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_agg_classes', f"{ESTROBERTA_RESULTS_DIR}/events_w_agg_class/main", 'main')

# agregeeritud klassidega (ilma eraldi modaalverbide kategooriata)
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_agg_classes_no_modal', f"{ESTROBERTA_RESULTS_DIR}/events_w_agg_class_no_modal/all", 'all')
fill_res_dict(estroberta_res, 'Est-RoBERTa_w_agg_classes_no_modal', f"{ESTROBERTA_RESULTS_DIR}/events_w_agg_class_no_modal/main", 'main')

### Est-RoBERTa event detection results

In [25]:
estroberta_res

{'Est-RoBERTa_no_classes': {'train_eval_all': {'train_eval_precision': 0.86,
   'train_eval_recall': 0.92,
   'train_eval_f1': 0.89},
  'final_test_all': {'final_test_precision': 0.83,
   'final_test_recall': 0.9,
   'final_test_f1': 0.86},
  'pred_tempf_all_horisont': {'pred_recall': 0.82},
  'pred_tempf_all_news': {'pred_recall': 0.83},
  'pred_tempf_all_rkogu': {'pred_recall': 0.77},
  'train_eval_main': {'train_eval_precision': 0.92,
   'train_eval_recall': 0.94,
   'train_eval_f1': 0.93},
  'pred_tempf_main_horisont': {'pred_recall': 0.82},
  'pred_tempf_main_news': {'pred_recall': 0.81},
  'pred_tempf_main_rkogu': {'pred_recall': 0.73},
  'final_test_main': {'final_test_precision': 0.88,
   'final_test_recall': 0.89,
   'final_test_f1': 0.88}},
 'Est-RoBERTa_w_classes': {'pred_tempf_all_horisont': {'pred_recall': 0.64},
  'pred_tempf_all_news': {'pred_recall': 0.65},
  'pred_tempf_all_rkogu': {'pred_recall': 0.49},
  'train_eval_all': {'train_eval_precision': 0.76,
   'train_eval_recall': 0.78,
   'train_eval_f1': 0.77},
  'final_test_all': {'final_test_precision': 0.72,
   'final_test_recall': 0.77,
   'final_test_f1': 0.74},
  'pred_tempf_main_horisont': {'pred_recall': 0.63},
  'pred_tempf_main_news': {'pred_recall': 0.64},
  'pred_tempf_main_rkogu': {'pred_recall': 0.51},
  'train_eval_main': {'train_eval_precision': 0.81,
   'train_eval_recall': 0.8,
   'train_eval_f1': 0.8},
  'final_test_main': {'final_test_precision': 0.76,
   'final_test_recall': 0.76,
   'final_test_f1': 0.76}},
 'Est-RoBERTa_w_agg_classes': {'pred_tempf_all_horisont': {'pred_recall': 0.73},
  'pred_tempf_all_news': {'pred_recall': 0.66},
  'pred_tempf_all_rkogu': {'pred_recall': 0.49},
  'train_eval_all': {'train_eval_precision': 0.79,
   'train_eval_recall': 0.82,
   'train_eval_f1': 0.81},
  'final_test_all': {'final_test_precision': 0.73,
   'final_test_recall': 0.77,
   'final_test_f1': 0.75},
  'pred_tempf_main_horisont': {'pred_recall': 0.63},
  'pred_tempf_main_news': {'pred_recall': 0.63},
  'pred_tempf_main_rkogu': {'pred_recall': 0.45},
  'train_eval_main': {'train_eval_precision': 0.83,
   'train_eval_recall': 0.82,
   'train_eval_f1': 0.83},
  'final_test_main': {'final_test_precision': 0.77,
   'final_test_recall': 0.75,
   'final_test_f1': 0.76}},
 'Est-RoBERTa_w_agg_classes_no_modal': {'pred_tempf_all_horisont': {'pred_recall': 0.68},
  'pred_tempf_all_news': {'pred_recall': 0.64},
  'pred_tempf_all_rkogu': {'pred_recall': 0.47},
  'train_eval_all': {'train_eval_precision': 0.79,
   'train_eval_recall': 0.78,
   'train_eval_f1': 0.78},
  'final_test_all': {'final_test_precision': 0.74,
   'final_test_recall': 0.75,
   'final_test_f1': 0.74},
  'pred_tempf_main_horisont': {'pred_recall': 0.63},
  'pred_tempf_main_news': {'pred_recall': 0.67},
  'pred_tempf_main_rkogu': {'pred_recall': 0.52},
  'train_eval_main': {'train_eval_precision': 0.81,
   'train_eval_recall': 0.83,
   'train_eval_f1': 0.82},
  'final_test_main': {'final_test_precision': 0.77,
   'final_test_recall': 0.81,
   'final_test_f1': 0.79}}}

In [26]:
pd.DataFrame.from_dict({(i,j): estroberta_res[i][j] 
                           for i in estroberta_res.keys() 
                           for j in estroberta_res[i].keys()},
                       orient='index')

                                                             train_eval_precision  \
Est-RoBERTa_no_classes             train_eval_all                            0.86
                                   train_eval_main                           0.92
Est-RoBERTa_w_classes              train_eval_all                            0.76
                                   train_eval_main                           0.81
Est-RoBERTa_w_agg_classes          train_eval_all                            0.79
                                   train_eval_main                           0.83
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                            0.79
                                   train_eval_main                           0.81
Est-RoBERTa_no_classes             final_test_all                             NaN
                                   final_test_main                            NaN
Est-RoBERTa_w_classes              final_test_all                             NaN
                                   final_test_main                            NaN
Est-RoBERTa_w_agg_classes          final_test_all                             NaN
                                   final_test_main                            NaN
Est-RoBERTa_w_agg_classes_no_modal final_test_all                             NaN
                                   final_test_main                            NaN
Est-RoBERTa_no_classes             pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN

                                                             train_eval_recall  \
Est-RoBERTa_no_classes             train_eval_all                         0.92
                                   train_eval_main                        0.94
Est-RoBERTa_w_classes              train_eval_all                         0.78
                                   train_eval_main                        0.80
Est-RoBERTa_w_agg_classes          train_eval_all                         0.82
                                   train_eval_main                        0.82
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                         0.78
                                   train_eval_main                        0.83
Est-RoBERTa_no_classes             final_test_all                          NaN
                                   final_test_main                         NaN
Est-RoBERTa_w_classes              final_test_all                          NaN
                                   final_test_main                         NaN
Est-RoBERTa_w_agg_classes          final_test_all                          NaN
                                   final_test_main                         NaN
Est-RoBERTa_w_agg_classes_no_modal final_test_all                          NaN
                                   final_test_main                         NaN
Est-RoBERTa_no_classes             pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN

                                                             train_eval_f1  \
Est-RoBERTa_no_classes             train_eval_all                     0.89
                                   train_eval_main                    0.93
Est-RoBERTa_w_classes              train_eval_all                     0.77
                                   train_eval_main                    0.80
Est-RoBERTa_w_agg_classes          train_eval_all                     0.81
                                   train_eval_main                    0.83
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                     0.78
                                   train_eval_main                    0.82
Est-RoBERTa_no_classes             final_test_all                      NaN
                                   final_test_main                     NaN
Est-RoBERTa_w_classes              final_test_all                      NaN
                                   final_test_main                     NaN
Est-RoBERTa_w_agg_classes          final_test_all                      NaN
                                   final_test_main                     NaN
Est-RoBERTa_w_agg_classes_no_modal final_test_all                      NaN
                                   final_test_main                     NaN
Est-RoBERTa_no_classes             pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN

                                                             final_test_precision  \
Est-RoBERTa_no_classes             train_eval_all                             NaN
                                   train_eval_main                            NaN
Est-RoBERTa_w_classes              train_eval_all                             NaN
                                   train_eval_main                            NaN
Est-RoBERTa_w_agg_classes          train_eval_all                             NaN
                                   train_eval_main                            NaN
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                             NaN
                                   train_eval_main                            NaN
Est-RoBERTa_no_classes             final_test_all                            0.83
                                   final_test_main                           0.88
Est-RoBERTa_w_classes              final_test_all                            0.72
                                   final_test_main                           0.76
Est-RoBERTa_w_agg_classes          final_test_all                            0.73
                                   final_test_main                           0.77
Est-RoBERTa_w_agg_classes_no_modal final_test_all                            0.74
                                   final_test_main                           0.77
Est-RoBERTa_no_classes             pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont                    NaN
                                   pred_tempf_all_news                        NaN
                                   pred_tempf_all_rkogu                       NaN
                                   pred_tempf_main_horisont                   NaN
                                   pred_tempf_main_news                       NaN
                                   pred_tempf_main_rkogu                      NaN

                                                             final_test_recall  \
Est-RoBERTa_no_classes             train_eval_all                          NaN
                                   train_eval_main                         NaN
Est-RoBERTa_w_classes              train_eval_all                          NaN
                                   train_eval_main                         NaN
Est-RoBERTa_w_agg_classes          train_eval_all                          NaN
                                   train_eval_main                         NaN
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                          NaN
                                   train_eval_main                         NaN
Est-RoBERTa_no_classes             final_test_all                         0.90
                                   final_test_main                        0.89
Est-RoBERTa_w_classes              final_test_all                         0.77
                                   final_test_main                        0.76
Est-RoBERTa_w_agg_classes          final_test_all                         0.77
                                   final_test_main                        0.75
Est-RoBERTa_w_agg_classes_no_modal final_test_all                         0.75
                                   final_test_main                        0.81
Est-RoBERTa_no_classes             pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont                 NaN
                                   pred_tempf_all_news                     NaN
                                   pred_tempf_all_rkogu                    NaN
                                   pred_tempf_main_horisont                NaN
                                   pred_tempf_main_news                    NaN
                                   pred_tempf_main_rkogu                   NaN

                                                             final_test_f1  \
Est-RoBERTa_no_classes             train_eval_all                      NaN
                                   train_eval_main                     NaN
Est-RoBERTa_w_classes              train_eval_all                      NaN
                                   train_eval_main                     NaN
Est-RoBERTa_w_agg_classes          train_eval_all                      NaN
                                   train_eval_main                     NaN
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                      NaN
                                   train_eval_main                     NaN
Est-RoBERTa_no_classes             final_test_all                     0.86
                                   final_test_main                    0.88
Est-RoBERTa_w_classes              final_test_all                     0.74
                                   final_test_main                    0.76
Est-RoBERTa_w_agg_classes          final_test_all                     0.75
                                   final_test_main                    0.76
Est-RoBERTa_w_agg_classes_no_modal final_test_all                     0.74
                                   final_test_main                    0.79
Est-RoBERTa_no_classes             pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_classes              pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_agg_classes          pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN
Est-RoBERTa_w_agg_classes_no_modal pred_tempf_all_horisont             NaN
                                   pred_tempf_all_news                 NaN
                                   pred_tempf_all_rkogu                NaN
                                   pred_tempf_main_horisont            NaN
                                   pred_tempf_main_news                NaN
                                   pred_tempf_main_rkogu               NaN

                                                             pred_recall
Est-RoBERTa_no_classes             train_eval_all                    NaN
                                   train_eval_main                   NaN
Est-RoBERTa_w_classes              train_eval_all                    NaN
                                   train_eval_main                   NaN
Est-RoBERTa_w_agg_classes          train_eval_all                    NaN
                                   train_eval_main                   NaN
Est-RoBERTa_w_agg_classes_no_modal train_eval_all                    NaN